#
# Work based on https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml
#
# Configuration: Add to _config.yml
# locale: "en-US"  [YOUR PREFERRED LOCALE]
#
# How to use:
# {{ site.data.ui-text[site.locale].<var_name> | default: 'text' }}

header:
  title: ""
  text: What do you want to build today?
  button: Tell Me More
  buttonlink: "#services"

services:
  title: "Services"
  text: "I provide help with technology and story-centered marketing."
  section: services
  list:
    - title: "Technology"
      desc: "I have worked in technology, ranging from customer support to web development to educational system designs for decades. Let's work together to uniquely implement technology in a way that builds value in your life and business."
      icon: fas fa-laptop
    - title: "Writing"
      desc: "We are all driven by stories. Connection to one another motivates our decisions and direct so much of what we accomplish. Let me help to clarify your story."
      icon: fas fa-pencil-alt
    - title: "Focus"
      desc: "Getting your message honed and directed is critical to generating meaningful impact both personally and professionally. Let's talk about your aims."
      icon: fas fa-dot-circle

portfolio:
  title: "Portfolio"
  text: "Lorem ipsum dolor sit amet consectetur."
  section: portfolio
  closebutton: "Close Project"

timeline:
  title: "Timeline"
  text: "A quick snapshot of my history in the creative use of technology."
  section: timeline
  # left is the default
  #start_align: "left"
  events:
    - title: "BeyondTrust"
      role: "Senior Director Education Resources"
      year: "2021 to Present"
      desc: "Promoted to director after successfully leading my lean team in consistently delivering training updates that incorporated customer feedback, product feature explanations, and increased emphasis on certification and continued education. Assembled and developed a team of six content designers empowered to deliver and maintain training materials for customers, sales and technical partners, and internal employees. Negotiated project needs between internal and external stakeholders to deliver training to accommodate broad audiences of varying skill levels. Maintained a best-in-class Net Promoter Score of over 40 and Customer Satisfaction Rating of over 90."
      image: assets/img/timeline/bt-logo.png
      alt:
    - title: "Hazelwood Laboratories"
      role: "Contracted Developer"
      year: "2020"
      desc: "I worked again with Joe Hazelwood and New Hat to build an arduino powered firefly wallpaper for the restrooms of Audrey restaurant in Nashville."
      image: assets/img/timeline/haz-logo.png
      alt: image alt text
    - title: "BeyondTrust"
      role: "Senior Manager eLearning"
      year: "2019 to 2021"
      desc: "Promoted to senior manager after successfully leading a critical tool migration project and developing a training roadmap that accommodated product engineers moving to a faster product release cadence using Agile workflow. Promoted to manager after leading my team to standardize course development processes and tool selection procedures. Expanded self-paced course coverage from 2 to 5+ products."
      image: assets/img/timeline/bt-logo.png
      alt:
    - title: "BeyondTrust"
      role: "Senior eLearning Developer"
      year: "2017 to 2019"
      desc: "As a self-paced training developer, designed and released online training material for global customers."
      image: assets/img/timeline/bt-logo.png
      alt:
    - title: "Hazelwood Laboratories"
      role: "Contracted Developer"
      year: "2015"
      desc: "Among my proudest projects was working with Joe Hazelwood to build a Raspberry Pi powered video multi-caster for OZ Nashville.  The project was featured in MagPi issue #33 and later in the 50 best projects issue."
      image: assets/img/timeline/haz-logo.png
      alt: image alt text
    - title: "BeyondTrust <em>(Bomgar)</em>"
      role: "Senior Instructor"
      year: "2014 to 2017"
      desc: "Rejoined the technology sector as product instructor delivering cyber security training to global customers, both virtually and in-person."
      image: assets/img/timeline/bg-logo.png
      alt: image alt text
    - title: "Barista Parlor"
      role: "Kitchen Manager"
      year: "2013"
      desc: "Took a break from providing support in high pressure environment and embraced a love of good food, coffee, and fun-loving teammates. Assembled a team that consistently prepped, prepared, and delivered excellent food that paired with specific coffee origins."
      image: assets/img/timeline/barista-parlor.png
      alt:
    - title: "Click Effects"
      role: "Product Support Engineer"
      year: "2006 to 2012"
      desc: "Support engineer resolving technical issue for operators in the NBA, MLB, and NFL during game day productions. Performed on-site installations and training for sport venues like Madison Square Garden and Staples Center."
      image: assets/img/timeline/clickeffects.png
      alt:
     # you can enforce the alignment
     # align: right
  end: "The story <br />starts <br />here"

about:
  title: "About Me"
  text: "in a nutshell"
  body: "My passion is centered around solving problems with people. I am a Product Education Director with experience including 3+ years leading people, 5+ years managing projects, and 2+ years building subscription-based training products. I am excited by understanding and supporting stakeholder needs while building value in a collaborative environment."
  section: about

clients:
  section: clients
  max-height: 100px
  horizontal-scrolling: "" #"yes/no"
  list:
    - title: "envato"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/envato.jpg
    - title: "designmodo"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/designmodo.jpg
    - title: "themeforest"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/themeforest.jpg
    - title: "Creative Market"
      url: https://github.com/raviriley/agency-jekyll-theme
      logo: assets/img/clients/creative-market.jpg

team:
  title: "OUR AMAZING TEAM"
  text: "Lorem ipsum dolor sit amet consectetur."
  subtext: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde. **Markdown** supported.
  section: team
  people:
    - name: "Kay Garland"
      role: "Lead Designer"
      image: assets/img/team/500x500.jpg
      social:
        - url: https://twitter.com
          icon: fab fa-twitter
        - url: https://facebook.com
          icon: fab fa-facebook-f
        - url: https://linkedin.com
          icon: fab fa-linkedin-in
    - name: "Larry Parker"
      role: "Lead Marketer"
      image: assets/img/team/2.jpg
      social:
        - url: https://twitter.com
          icon: fab fa-twitter
        - url: https://facebook.com
          icon: fab fa-facebook-f
        - url: https://linkedin.com
          icon: fab fa-linkedin-in
    - name: "Diana Perterson"
      role: "Lead Developer"
      image: assets/img/team/500x500.jpg
      social:
        - url: https://twitter.com
          icon: fab fa-twitter
        - url: https://facebook.com
          icon: fab fa-facebook-f
        - url: https://linkedin.com
          icon: fab fa-linkedin-in

contact:
  title: "Contact Us"
  text: "Lorem ipsum or call 123456789"
  section: contact
  name: "Name*"
  name-validation: "Please enter your name."
  email: "Email*"
  email-validation: "Please enter your email address."
  phone: "Phone Number"
  phone-validation: "Please enter your phone number."
  message: "Message*"
  message-validation: "Please enter a message."
  subject: "Contact Form Submission"
  submit: "Send Message"

footer:
  legal: "Privacy Policy"
  social:
    - url: https://twitter.com/philliplehner
      icon: "fab fa-twitter"
    - url: https://www.linkedin.com/in/phillip-lehner-b808b11a/
      icon: "fab fa-linkedin-in"
    - url: https://github.com/Pilipo
      icon: "fab fa-github"
